---
output: pdf_document
---
#__Introduction__

The following report is based on the "Individual household electric power consumption dataset" obtained from the [UC Irvine Machine Learning Repository][1], a popular repository for machine learning datasets.The report was submitted in partial fulfillment of the requirements for the [Coursera][2] course [Exploratory Data Analysis][3] run by John Hopkins University.
```{r}
```


* __Description__: Measurements of electric power consumption in
one household with a one-minute sampling rate over a period of almost
4 years. Different electrical quantities and some sub-metering values
are available.


The following descriptions of the 9 variables in the dataset were obtained from [https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption][4]

__Date__: Date in format dd/mm/yyyy  
__Time__: time in format hh:mm:ss  
__Global_active_power__: household global minute-averaged active power (in kilowatt)  
__Global_reactive_power__: household global minute-averaged reactive power (in kilowatt)   
__Voltage__: minute-averaged voltage (in volt)   
__Global_intensity__: household global minute-averaged current intensity (in ampere)   
__Sub_metering_1__: energy sub-metering No. 1 (in watt-hour of active energy). It corresponds to the kitchen, containing mainly a dishwasher, an oven and a microwave (hot plates are not electric but gas powered).  
__Sub_metering_2__: energy sub-metering No. 2 (in watt-hour of active energy). It corresponds to the laundry room, containing a washing-machine, a tumble-drier, a refrigerator and a light.  
__Sub_metering_3__: energy sub-metering No. 3 (in watt-hour of active energy). It corresponds to an electric water-heater and an air-conditioner. 
 

## Loading the data





When loading the dataset into R, please consider the following:

* The dataset has 2,075,259 rows and 9 columns. First
calculate a rough estimate of how much memory the dataset will require
in memory before reading into R. Make sure your computer has enough
memory (most modern computers should be fine).

* We will only be using data from the dates 2007-02-01 and
2007-02-02. One alternative is to read the data from just those dates
rather than reading in the entire dataset and subsetting to those
dates.

* You may find it useful to convert the Date and Time variables to
Date/Time classes in R using the `strptime()` and `as.Date()`
functions.

* Note that in this dataset missing values are coded as `?`.

[1]: http://archive.ics.uci.edu/ml/
[2]: https://www.coursera.org/
[3]: https://www.coursera.org/learn/exploratory-data-analysis
[4]: https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption